
# tap repositories and their packages

tap homebrew/core
brew aom
brew autoconf
brew autojump
brew automake
brew bat
brew cairo
brew cmake
brew cmatrix
brew cmus
brew coreutils
brew docker
brew faad2
brew fd
brew ffmpeg
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gdbm
brew genact
brew gettext
brew ghostscript
brew git
brew glib
brew gmp
brew gperftools
brew gradle
brew graphite2
brew harfbuzz
brew htop
brew icu4c
brew iftop
brew isl
brew jpeg
brew lame
brew leveldb
brew libao
brew libass
brew libcue
brew libevent
brew libffi
brew libidn2
brew libimobiledevice
brew libmpc
brew libogg
brew libplist
brew libpng
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libvorbis
brew libvpx
brew libxml2
brew little-cms2
brew mad
brew mas
brew midnight-commander
brew mp4v2
brew mpfr
brew ncdu
brew ncurses
brew nginx
brew nmap
brew node
brew opencore-amr
brew openssl
brew opus
brew pcre
brew pcre2
brew peco
brew pixman
brew pkg-config
brew prettyping
brew python
brew python@2
brew qt
brew readline
brew rtmpdump
brew s-lang
brew sdl2
brew sl
brew snappy
brew speex
brew sqlite
brew theora
brew tig
brew tmux
brew trash
brew tree
brew usbmuxd
brew wget
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl
brew zsh
brew zsh-autosuggestions
brew zsh-completions
brew zsh-syntax-highlighting

tap homebrew/bundle

tap homebrew/cask-versions

tap homebrew/cask
cask adobe-creative-cloud
cask blender
cask daisydisk
cask discord
cask firestormos
cask free-download-manager
cask google-chrome
cask grammarly
cask insomniax
cask istat-menus
cask karabiner-elements
cask microsoft-office
cask openemu
cask qq
cask sizeup
cask sogouinput
cask sublime-text
cask thunder

tap argon/mas

tap ethereum/ethereum

tap mas-cli/tap

tap paritytech/paritytech

tap rcmdnk/file
brew brew-file

tap sambadevi/powerlevel9k
brew powerlevel9k

# Other Cask applications
cask alfred
cask carbon-copy-cloner
cask desmume
cask docker
cask franz
cask google-backup-and-sync
cask google-japanese-ime
cask handbrake
cask intellij-idea
cask iterm2
cask kitematic
cask mplayerx
cask plistedit-pro
cask rescuetime
cask slack
cask spotify
cask the-unarchiver
cask xquartz

# App Store applications
# appstore 1436953057 GhosteryLite (1.0.0)
# appstore 409907375 Remote Desktop (3.9)
# appstore 1385985095 uBlock (1.3)
# appstore 836500024 WeChat (2.3.23)

