
# tap repositories and their packages

tap homebrew/core
brew aom
brew autoconf
brew autojump
brew automake
brew bat
brew cairo
brew cmake
brew cmatrix
brew cmus
brew coreutils
brew cscope
brew diff-so-fancy
brew docker
brew faad2
brew fd
brew ffmpeg
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gdbm
brew genact
brew geoip
brew gettext
brew ghostscript
brew giflib
brew git
brew glib
brew gmp
brew gnutls
brew go
brew gperftools
brew gradle
brew graphite2
brew harfbuzz
brew htop
brew icu4c
brew iftop
brew isl
brew jpeg
brew lame
brew leptonica
brew leveldb
brew libao
brew libass
brew libbluray
brew libcue
brew libevent
brew libffi
brew libidn2
brew libimobiledevice
brew libmpc
brew libogg
brew libplist
brew libpng
brew libsamplerate
brew libsndfile
brew libsoxr
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libvorbis
brew libvpx
brew libxml2
brew little-cms2
brew lua
brew mad
brew mas
brew midnight-commander
brew mp4v2
brew mpfr
brew ncdu
brew ncurses
brew nettle
brew nmap
brew node
brew opencore-amr
brew openjpeg
brew openssl
brew opus
brew p11-kit
brew pcre
brew pcre2
brew peco
brew pixman
brew pkg-config
brew prettyping
brew python
brew qt
brew readline
brew reaver
brew rtmpdump
brew rubberband
brew rust
brew rustup-init
brew s-lang
brew sdl2
brew sl
brew snappy
brew speex
brew sqlite
brew tesseract
brew theora
brew tig
brew tmux
brew tree
brew unbound
brew usbmuxd
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl
brew zsh
brew zsh-autosuggestions
brew zsh-completions
brew zsh-syntax-highlighting

tap homebrew/bundle

tap homebrew/cask-versions

tap homebrew/cask
cask adobe-creative-cloud
cask blender
cask docker
cask firestormos
cask free-download-manager
cask google-backup-and-sync
cask google-japanese-ime
cask handbrake
cask intellij-idea
cask iterm2
cask karabiner-elements
cask microsoft-office
cask rescuetime
cask sizeup
cask slack
cask spotify
cask the-unarchiver
cask tor-browser
cask zeronet

tap argon/mas

tap ethereum/ethereum

tap iikira/baidupcs
brew baidupcs-go

tap mas-cli/tap

tap paritytech/paritytech

tap rcmdnk/file
brew brew-file

tap sambadevi/powerlevel9k
brew powerlevel9k

# Other Cask applications
cask alfred
cask carbon-copy-cloner
cask discord
cask energybar
cask franz
cask gitkraken
cask google-chrome
cask grammarly
cask istat-menus
cask java
cask kitematic
cask qq
cask shadowsocksx-ng
cask skype
cask sogouinput
cask sublime-text
cask wireshark
cask zenmap

# App Store applications
appstore 409907375 com.apple.RemoteDesktop (3.9)
appstore 937984704 com.if.Amphetamine (4.1.6)
appstore 836500024 WeChat (2.3.24)
