#!/usr/bin/env bash

declare -i verboseMode=1

usage="Usage: $0 [-h|q|v]\n
    -h\tHelp
    -q\tQuiet mode
    -v\tVerbose mode"

while getopts "hqv" opt;
    do case ${opt} in
        h ) echo -e ${usage}
            exit 1;;
        q ) verboseMode=0;;
        v ) verboseMode=1;;
    esac
done
shift $(($OPTIND - 1))

if [[ -f .pckeyboard.json ]]; then # switch to Mac
    command cp -f mackeyboard.json karabiner.json
    command mv -f .pckeyboard.json pckeyboard.json
    command mv -f mackeyboard.json .mackeyboard.json
    if [[ -n verboseMode ]]; then echo "Mac keyboard active in Karabiner Elements!"; fi
elif [[ -f .mackeyboard.json ]]; then # switch to PC
    command cp -f pckeyboard.json karabiner.json
    command mv -f pckeyboard.json .pckeyboard.json
    command mv -f .mackeyboard.json mackeyboard.json
    if [[ -n verboseMode ]]; then echo "PC keyboard active in Karabiner Elements!"; fi
else # unknown state - default to Mac
    command cp -f mackeyboard.json karabiner.json
    command mv -f mackeyboard.json .mackeyboard.json
    echo "Current state unknown - defaulting to Mac keyboard active in Karabiner Elements!"
fi